### ISSUE TITLE
signal_pending() is undefined on Ubuntu 16.04

### ISSUE THREAD

**Issue by ledlo** [esposem/Kernel_UDP#1]
error: implicit declaration of function ‘signal_pending’ [-Werror=implicit-function-declaration]
   while ((troughput.count < SIZE_SAMPLE) && !(kthread_should_stop() || signal_pending(current)))

**Comment by esposem** [comment]
Hi, can you post your kernel version? It's the output of `uname -r` in your terminal.
Btw, signal_pending is defined on linux/sched.h,  so adding #include <linux/sched.h> should work. 
Let me know.

**Comment by esposem** [comment]
included `<linux/sched.h>` where needed
